keep plugin works when xbox live API is down
caused
```log
[ERROR] Failed to sync friends
com.rtm516.mcxboxbroadcast.core.exceptions.XboxFriendsException: HTTP/1.1 header parser received no bytes
        at com.rtm516.mcxboxbroadcast.core.SessionManager.getXboxFriends(SessionManager.java:300)
```